leftnav:
- identifier: 52aeb0c8-c338-b397-7814-e1dadc306dfb
  name: Syllabus
  pageRef: /pages/syllabus
  weight: 10
- identifier: 90f171de-9032-4e2e-1299-d387eeb0c42e
  name: Calendar
  pageRef: /pages/calendar
  weight: 20
- identifier: 81a86953-ad1f-75ec-fbfa-25e2d46ae338
  name: Readings
  pageRef: /pages/readings
  weight: 30
- identifier: 777cede0-47d9-3091-8c4d-19f2747d785c
  name: Lecture Notes
  pageRef: /pages/lecture-notes
  weight: 40
- identifier: db75387b-e404-28ec-2779-7629fa684c86
  name: Assignments
  pageRef: /pages/assignments/
  weight: 50
- identifier: cfe309f1-1998-a449-dbd8-f4a60fe253ce
  name: Assignment 1
  pageRef: /pages/assignments/assignment-1
  parent: db75387b-e404-28ec-2779-7629fa684c86
  weight: 60
- identifier: 757b3c1f-d3a1-96fd-822a-ed6bca8e82d2
  name: Assignment 2
  pageRef: /pages/assignments/assignment-2
  parent: db75387b-e404-28ec-2779-7629fa684c86
  weight: 70
- identifier: 4745da94-d8f7-59c3-5d35-c7ca2445bc52
  name: Assignment 3
  pageRef: /pages/assignments/assignment-3
  parent: db75387b-e404-28ec-2779-7629fa684c86
  weight: 80
- identifier: 67a5c9ec-d09e-429b-59a6-f1d8beae2a8c
  name: Assignment 4
  pageRef: /pages/assignments/assignment-4
  parent: db75387b-e404-28ec-2779-7629fa684c86
  weight: 90
- identifier: d7466cf6-f325-faed-9651-e6fcb4c2e7cc
  name: Assignment 5
  pageRef: /pages/assignments/assignment-5
  parent: db75387b-e404-28ec-2779-7629fa684c86
  weight: 100
- identifier: 781acbf5-746c-da93-05d8-b293bcf58acb
  name: Assignment 6
  pageRef: /pages/assignments/assignment-6
  parent: db75387b-e404-28ec-2779-7629fa684c86
  weight: 110
- identifier: e07c5a67-d085-f558-afb2-6f117ab511f7
  name: Assignment 7
  pageRef: /pages/assignments/assignment-7
  parent: db75387b-e404-28ec-2779-7629fa684c86
  weight: 120
- identifier: 287588c6-5191-7422-7320-c0f12d170078
  name: Assignment 8
  pageRef: /pages/assignments/assignment-8
  parent: db75387b-e404-28ec-2779-7629fa684c86
  weight: 130
- identifier: 3ff4d4c5-9272-62d6-3e1d-3c18ff020a67
  name: Final Project
  pageRef: /pages/final-project/
  weight: 140
- identifier: 3e63711d-b2b1-c1b4-f7fa-768e0df1e611
  name: Project Proposal
  pageRef: /pages/final-project/project-proposal
  parent: 3ff4d4c5-9272-62d6-3e1d-3c18ff020a67
  weight: 150
- identifier: 0b733ad3-4f93-c11c-ca5f-169ed245f989
  name: Presentations
  pageRef: /pages/final-project/presentations
  parent: 3ff4d4c5-9272-62d6-3e1d-3c18ff020a67
  weight: 160
- identifier: 12918cc4-e09a-772c-b8f0-c9ea6f5adbac
  name: Written Report
  pageRef: /pages/final-project/written-report
  parent: 3ff4d4c5-9272-62d6-3e1d-3c18ff020a67
  weight: 170
